services:
  redis:
    image: redis:7-alpine
    container_name: jesse_redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    container_name: jesse_postgres
    environment:
      POSTGRES_DB: jesse_db
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
